version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: migueldemrd
      POSTGRES_DB: my-database
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
